apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  type: LoadBalancer
  selector:
    app: pod-web
  ports:
  - port: 3333
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-web
  template:
    metadata:
      labels:
        app: pod-web
    spec:
      containers:
      - name: container-web
        image: cisko6/web-to-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
