apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        ports:
          - containerPort: 5050
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@admin.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: mypassword
        - name: PGADMIN_LISTEN_PORT
          value: "5050"

---

apiVersion: v1
kind: Service
metadata:
  name: pg-svc
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 30001
