apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-cm
  namespace: mongo
data:
  database-url: mongo-svc

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
