apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        env:
          - name: GET_HOSTS_FROM
            value: dns
        ports:
        - containerPort: 6379